name: 'PHP Code Quality'
description: 'Check code quality of php files and code'
inputs:
  php_version:
    description: 'PHP version to use'
    required: false
    default: '8.2'
runs:
  using: 'docker'
  image: ghcr.io/ordinaryphp/code-quality:dev-php${{ inputs.php_version }}
branding:
  icon: 'check'
  color: 'green'