name: "Build, test, and deploy"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - dev
    tags:
      - '**'
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  build-push:
    uses: ./.github/workflows/build-push-test.yml
    with:
      php-version: "8.2"
    secrets: inherit
