name: "Build, test, and deploy"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - dev
    tags:
      - '**'
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  build-push:
    strategy:
      matrix:
        php-version: [ "8.2" ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{var.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{github.repository}}:${{github.ref_name}}
            ${{var.DOCKERHUB_USER}}/${{github.event.repository.name}}:${{github.ref_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  lint:
    needs: [ build-push ]
    strategy:
      matrix:
        php-version: [ "8.2" ]

    runs-on: ubuntu-latest
    container: ghcr.io/${{github.repository}}:${{github.ref_name}}
    steps:
      - name: Lint
        run: cd /code-quality && phplint
  static-analysis:
    needs: [ build-push ]
    strategy:
      matrix:
        php-version: [ "8.2" ]

    runs-on: ubuntu-latest
    container: ghcr.io/${{github.repository}}:${{github.ref_name}}
    steps:
      - name: Static Analysis
        run: cd /code-quality && psalm
  code-style:
    needs: [ build-push ]
    strategy:
      matrix:
        php-version: [ "8.2" ]

    runs-on: ubuntu-latest
    container: ghcr.io/${{github.repository}}:${{github.ref_name}}
    steps:
      - name: Code Style
        run: cd /code-quality && phpcs